apiVersion: build.openshift.io/v1 
kind: BuildConfig 
metadata: 
"  name: sentiment-backend" 
spec: 
"  source:" 
"    type: Git" 
"    git:" 
"      uri: https://github.com/franalfa/sentiment-backend.git" 
"    contextDir: ." 
"  strategy:" 
"    type: Docker" 
"    dockerStrategy:" 
"      dockerfilePath: Dockerfile" 
"  output:" 
"    to:" 
"      kind: ImageStreamTag" 
"      name: sentiment-backend:latest" 
"  triggers:" 
"    - type: GitHub" 
"      github:" 
"        secret: mywebhooksecret" 
"    - type: ConfigChange" 
"    - type: ImageChange" 
